### PR TITLE
Fix Daycare integration

### PR DESCRIPTION
**Pull request by landonjw**

### CODE REVIEW

**Comment by danorris709** [comment]
If the other mod breaks it's their fault given I didn't edit the API

**Comment by landonjw** [comment]
By breaking an explicit contract within the class, it is your fault. But please, continue to deny responsibility and argue about wishy washy 'best practices' while you continue to modify bytecode at runtime and break other systems that have been stable for years, instead of adding one marker.

index

**Comment by danorris709** [comment]
> By breaking an explicit contract within the class, it is your fault. But please, continue to deny responsibility and argue about wishy washy 'best practices' while you continue to modify bytecode at runtime and break other systems that have been stable for years, instead of adding one marker.
> 
> index
> 

I broke a system that has not existed for several years for one.

For two, I'm simply following the best practices that are well documented online.

For three, just because I chose to use mixins to improve the servers performance doesn't explicitly break any form of best practices.

For the fourth, the class doesn't say anywhere that it is to be serialized in the decompiled code (which is the place you should be looking). If you were to follow the SRP it'd explicitly be clear it's not a class for serializing. 

Now stop harassing me.

**Comment by NickImpact** [comment]
The Pokemon class, serializable and deserializable by NBT, which directly maps to JSON nowadays. A class designed by Hiroku to be JSON compatible. Must be absolutely crazy to assume such heresy. We know it takes a lot of effort to add a single keyword that’ll give other developers the ability to use GSON directly again, so we understand if you don’t want to hurt those delicate fingers of yours. 

Also, hiiiiiiiiiiiiiiii, it’s me!

**Comment by danorris709** [comment]
> The Pokemon class, serializable and deserializable by NBT, which directly maps to JSON nowadays. A class designed by Hiroku to be JSON compatible. Must be absolutely crazy to assume such heresy. We know it takes a lot of effort to add a single keyword that’ll give other developers the ability to use GSON directly again, so we understand if you don’t want to hurt those delicate fingers of yours.
> 
> Also, hiiiiiiiiiiiiiiii, it’s me!

Hi? I don't think I've spoken to you before.

As for that method, I'm glad you brought it up actually. 
The NBT maps to JSON, yes. However, I don't see that method wrapping the entire class (being the Pokemon class) in the Gson serialize method. Do you know the reason for this? I do! It's because it's not supposed to be.

**Pull request closed without merging**
